# roles/frontend/tasks/main.yml
---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Configure nginx for petclinic
  template:
    src: petclinic.conf.j2
    dest: /etc/nginx/conf.d/petclinic.conf
  notify: reload nginx

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
