# ./ansible/inventory/hosts.yml
all:
  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

frontend:
  hosts:
    frontend:
      ansible_host: 74.248.138.84
      ansible_ssh_common_args: ''
  vars:
    frontend_port: 4200
    load_balancing: "OFF"
    backend_host: "10.0.0.6"
    backend_port: 9966

backend:
  hosts:
    backend1:
      ansible_host: 10.0.0.6
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q azureuser@74.248.138.84"'
  vars:
    backend_port: 9966
    mysql_host: "10.0.0.8"
    mysql_port: 3306

mysql:
  hosts:
    mysql1:
      ansible_host: 10.0.0.8
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q azureuser@74.248.138.84"'
  vars:
    mysql_port: 3306