# ./ansible/inventory/hosts.yml
all:
  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

frontend:
  hosts:
    frontend:
      ansible_host: 74.248.147.21
      ansible_ssh_common_args: ''
  vars:
    frontend_port: 4200
    load_balancing: "ON"
    backend_host: "10.0.0.5"
    backend_port: 9966
    backend2_host: "10.0.0.7"
    backend2_port: 9966

backend:
  hosts:
    backend1:
      ansible_host: 10.0.0.5
      ansible_ssh_common_args: '-J azureuser@74.248.147.21'
    backend2:
      ansible_host: 10.0.0.7
      ansible_ssh_common_args: '-J azureuser@74.248.147.21'
  vars:
    backend_port: 9966
    mysql_host: "10.0.0.8"
    mysql_port: 3306
    mysql_slave_host: "10.0.0.9"
    mysql_slave_port: 3307

mysql-master:
  hosts:
    mysql-master:
      ansible_host: 10.0.0.8
      ansible_ssh_common_args: '-J azureuser@74.248.147.21'
  vars:
    mysql_port: 3306
    mysql_master_port: 3306
    mysql_slave_host: 10.0.0.9

mysql-slave:
  hosts:
    mysql-slave:
      ansible_host: 10.0.0.9
      ansible_ssh_common_args: '-J azureuser@74.248.147.21'
  vars:
    mysql_port: 3306
    mysql_master_host: 10.0.0.8
    mysql_master_port: 3306
    mysql_slave_port: 3307
