---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create petclinic database
  mysql_db:
    name: petclinic
    state: present

- name: Create petclinic user
  mysql_user:
    name: petclinic
    password: petclinic
    priv: 'petclinic.*:ALL'
    host: '%'
    state: present

- name: Create replication user
  mysql_user:
    name: repl_petclinic
    password: repl_petclinic
    host: "{{ mysql_slave_host }}"
    priv: '*.*:REPLICATION SLAVE'
    state: present

- name: Configure MySQL master
  template:
    src: master.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql
