# roles/mysql/tasks/slave.yml
---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Configure MySQL slave
  template:
    src: slave.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql

- name: Wait for MySQL to start
  wait_for:
    port: "{{ mysql_slave_port }}"

- name: Configure replication
  mysql_replication:
    mode: changemaster
    master_host: "{{ mysql_master_host }}"
    master_port: "{{ mysql_master_port }}"
    master_user: repl_petclinic
    master_password: repl_petclinic
    master_auto_position: yes

- name: Start slave
  mysql_replication:
    mode: startslave
