- name: Deploy Spring Petclinic
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install basic dependencies
      apt:
        name:
          - curl
          - git
          - apt-transport-https
        state: present

- name: Configure Database
  hosts: mysql
  become: yes
  roles:
    - role: mysql
      tasks_from: main.yml

- name: Configure Backend
  hosts: backend
  become: yes
  roles:
    - backend

- name: Configure Frontend
  hosts: frontend
  become: yes
  roles:
    - frontend
