# roles/mysql-master/tasks/main.yml
---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL Python dependencies
  apt:
    name:
      - python3-pymysql
      - python3-mysqldb
    state: present

- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Configure MySQL master
  template:
    src: master.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql

- name: Z
  command: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
  changed_when: false

- name: S
  copy:
    dest: /root/.my.cnf
    content: |
      [client]
      user=root
      password=root
    mode: '600'

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Wait for MySQL to start
  wait_for:
    port: "{{ mysql_master_port }}"
    delay: 10

- name: Create petclinic database
  mysql_db:
    name: petclinic
    state: present

- name: Create petclinic user
  mysql_user:
    name: petclinic
    password: petclinic
    priv: 'petclinic.*:ALL'
    host: '%'
    state: present

- name: Create replication user
  mysql_user:
    name: repl_petclinic
    password: repl_petclinic
    host: "{{ mysql_slave_host }}"
    priv: '*.*:REPLICATION SLAVE'
    state: present